-- MySQL Script generated by MySQL Workbench
-- Mon Jan 25 13:11:42 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laravel_basica` DEFAULT CHARACTER SET utf8 ;
USE `laravel_basica` ;

-- -----------------------------------------------------
-- Table `laravel_basica`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel_basica`.`clients` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel_basica`.`works`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel_basica`.`works` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NULL,
  `image` VARCHAR(45) NULL,
  `inSlider` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `client_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_works_clients_idx` (`client_id` ASC),
  CONSTRAINT `fk_works_clients`
    FOREIGN KEY (`client_id`)
    REFERENCES `laravel_basica`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel_basica`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel_basica`.`tags` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel_basica`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel_basica`.`categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel_basica`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel_basica`.`posts` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `categorie_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_posts_categories1_idx` (`categorie_id` ASC) ,
  CONSTRAINT `fk_posts_categories1`
    FOREIGN KEY (`categorie_id`)
    REFERENCES `laravel_basica`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel_basica`.`works_has_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel_basica`.`works_has_tags` (
  `work_id` INT UNSIGNED NOT NULL,
  `tag_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`work_id`, `tag_id`),
  INDEX `fk_works_has_tags_tags1_idx` (`tag_id` ASC) ,
  INDEX `fk_works_has_tags_works1_idx` (`work_id` ASC) ,
  CONSTRAINT `fk_works_has_tags_works1`
    FOREIGN KEY (`work_id`)
    REFERENCES `laravel_basica`.`works` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_works_has_tags_tags1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `laravel_basica`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
