INSERT INTO works (id,title,content,image,inSlider,created_at,updated_at,client_id)
VALUES
(11,"mi pede, nonummy ut,","risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla","cursus non, egestas a,","0","2021-04-13 17:57:34","2020-05-06 19:59:11",11),
(12,"Donec nibh enim, gravida sit amet,","libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend,","magna nec quam. Curabitur","1","2021-11-17 18:49:40","2020-09-16 03:00:14",12),
(13,"velit","Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam","quam a felis ullamcorper","1","2021-01-18 15:19:45","2020-08-06 13:30:44",13),
(14,"sed orci lobortis augue scelerisque mollis. Phasellus libero","quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci","ante lectus convallis est,","0","2020-04-16 22:25:50","2020-07-30 13:39:19",14),
(15,"nonummy ac, feugiat non, lobortis quis, pede. Suspendisse","auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque","elementum, lorem ut aliquam","1","2020-02-03 13:35:24","2020-09-03 18:07:13",15),
(16,"rutrum eu, ultrices sit amet, risus. Donec nibh enim,","natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient","risus. Nulla eget metus","0","2020-07-20 11:13:58","2021-12-21 15:26:16",16),
(17,"elementum, dui quis","sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla","congue. In scelerisque scelerisque","0","2020-07-14 00:47:36","2020-04-28 20:40:11",17),
(18,"ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu.","enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum","orci. Ut semper pretium","1","2021-11-08 18:39:49","2021-01-01 08:01:50",18),
(19,"felis ullamcorper viverra. Maecenas iaculis","facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam","In lorem. Donec elementum,","1","2021-09-20 21:03:32","2020-03-27 13:04:30",19),
(20,"tincidunt aliquam arcu. Aliquam ultrices iaculis odio.","sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim.","id risus quis diam","0","2021-02-20 11:45:44","2020-06-19 23:07:23",20);
